### ISSUE TITLE
Удалить секретный ключ из исходного кода.

### ISSUE THREAD

**Issue by yanwork** [umnik1/yaamp#15]
https://github.com/umnik1/yaamp/blob/d74522e3411788dc517bf4998baef989ee5ea18b/services/UserService.d.ts#L20C59-L20C59

**Comment by yanwork** [comment]
К сожалению, с помощью этого кода злоумышленник сможет получить доступ к данным ваших пользователей,  список данных в картинке ниже.
<img width="475" alt="Screenshot 2023-11-10 at 19 24 04" src="https://github.com/umnik1/yaamp/assets/1057784/6acc9fe0-9926-4793-ba2a-28c6e8ce6254">

Всех ваших пользователей.

**Comment by suntehnik** [comment]
Неплохо бы зарепортить в Я, чтобы закинули ключЪ в черный список.

**Comment by umnik1** [comment]
> Неплохо бы зарепортить в Я, чтобы закинули ключЪ в черный список.

Код не активен уже давно + Это код самого Яндекса.

Метод авторизации через логин/пароль уже давно не работает, поэтому бессмысленно.
