### ISSUE TITLE
Failed to parse skin после перезапуска программы

### ISSUE THREAD

**Issue by seirawave** [umnik1/yaamp#17]
Запустил в первый раз, спокойно вошёл в аккаунт и проверил проигрывание музыки, закрыл, спустя небольшое время открыл снова и выводится окно с "Failed to parse skin" и закрывается окно с винампом 

win11 22h2, на установочной версии
![Screenshot_7113](https://github.com/umnik1/yaamp/assets/101430396/2fb44868-b697-4575-8d65-b6b80fff1444)

**Comment by seirawave** [comment]
Помогло. Благодарю!

**Comment by flopyssdareal** [comment]
Спасибо!

**Comment by Zzoomrus** [comment]
У кого та же ситуация на MacOS вот путь до файла skin.json - /Users/ИМЯ_ПОЛЬЗОВАТЕЛЯ/Library/Application Support/yaamp/skin.json

**Comment by umnik1** [comment]
**Поправлено в версии 0.0.2.**
