### ISSUE TITLE
Проблема с перетаскиванием окна

### ISSUE THREAD

**Issue by vlaadoo** [umnik1/yaamp#18]
На Windows не перетаскивается окно приложения на второй монитор
Если попробовать перенести через Win+Shift+*стрелка влево/вправо*, то окно будто повторяет размеры основного экрана:
![Screenshot_4](https://github.com/umnik1/yaamp/assets/63056620/27609a5c-37b6-4f30-ac30-ca42f6e66609)
(скрин приложен с вертикального монитора)

Выглядит так, будто при запуске прога занимает полный экран (в моем случае оно полностью занимает горизонтальный монитор и на вертикальном мониторе окно все также выглядит горизонтальным) и после окно плеера перетягивается только в пределах этого окна.

**Comment by atrest** [comment]
и поэтому же поводу если включить плеер на фоне окна с ютубом то в ютубе будет черный экран

**Comment by DzenDyn** [comment]
В линукс та же проблема с перетаскиванием.
Ubuntu 23.04

**Comment by devZu9** [comment]
Я тоже заметил это только, когда решил перетянуть плеер на второй монитор. Он просто "упирается" в край и не хочет "переползать". Но Shift + Win + Стрелка (влево-вправо) его перекидывает. Видимо действительно создаётся какое-то виртуально-прозрачное браузерное окно, т.к. в основе Electron -> Chrome

**Comment by stanislav-mikov** [comment]
> Я тоже заметил это только, когда решил перетянуть плеер на второй монитор. Он просто "упирается" в край и не хочет "переползать". Но Shift + Win + Стрелка (влево-вправо) его перекидывает. Видимо действительно создаётся какое-то виртуально-прозрачное браузерное окно, т.к. в основе Electron -> Chrome

Да, проблема есть, спасибо за лайфхак )

**Comment by spynal** [comment]
debian12 + cinnamon
такая же проблема, отображается только на 2-м (дополнительном) мониторе, переместить на 1-й (основной) не получается

**Comment by igorpnk** [comment]
С тем, что винамп занимает виртуально весь монитор, иногда возникает неприятный эффект - невозможно переключиться на другое приложение или на иконки рабочего стола. Видимо кликая на них, я по факту кликаю в винамп. Как воспроизвести: перевести в компактный режим сначала проигрыватель, потом эквалайзер, потом плейлист. Все далее невозможно работать с рабочим столом.

**Comment by autogen-travel** [comment]
На mac кроме проблемы с перетаскиванием есть еще и проблема с потерей фокуса на приложении.
Т.е. винамп становится как-бы прозрачным для курсора. И нужно принудительно активировать его, кликнув по иконке в доке или Alt+Tab или еще как-то. Ну и при скроллинге (колесико мышки) меняется громкость.

https://github.com/umnik1/yaamp/assets/13348823/fcb450db-76d3-4d2e-ab6c-d986cccc08e2

**Comment by umnik1** [comment]
**Поправлено в версии 0.0.2, пожалуйста проверьте.**

**Comment by Kiread-work** [comment]
@umnik1 теперь перетаскивается
появились новые баги, но этот можно закрывать (и лучше это сразу делать вместо комментирования, пользователи должны заводить новые заявки по новые проявлениям)

Если вести переписку в одном дефекте, это превратится в кашу из лапши (как пример см #58 )
