### ISSUE TITLE
Перетаскивание на маке между экранами

### ISSUE THREAD

**Issue by Zig1375** [umnik1/yaamp#43]
На маке не возможно перетащить окно на другой монитор

**Comment by antonsizikov** [comment]
Тоже столкнулся с проблемой на macOS. Пока что получается перетаскивать с помощью Mission Control.

**Comment by panason** [comment]
ubuntu 23.04 +

**Comment by igorpnk** [comment]
На винде можно перенести хоткеем Win + Shift + стрелка.

**Comment by birb2345345** [comment]
> На винде можно перенести хоткеем Win + Shift + стрелка.

На убунту тоже актуально

**Comment by Zig1375** [comment]
Перетащить можно, но костылями. Любые другие окна можно просто перетащить мышкой.

**Comment by umnik1** [comment]
Исправлено в версии 0.0.2
