### ISSUE TITLE
Невозможно разлогиниться или сменить аккаунт

### ISSUE THREAD

**Issue by t0hab** [umnik1/yaamp#51]
В приложении нет возможности сменить аккаунт пользователя или разлогиниться.

**Comment by devZu9** [comment]
А вы читали информацию на главной странице плеера? https://yaamp.ru/ 

![2023-11-17_13-37_44](https://github.com/umnik1/yaamp/assets/45079090/a62384b3-ccd5-4f3e-9a4c-069475b0e58b)

**Comment by umnik1** [comment]
**Исправлено в версии 0.0.2**
