### ISSUE TITLE
Failed to parse skin

### ISSUE THREAD

**Issue by Andrey140193** [umnik1/yaamp#65]
![Untitled](https://github.com/umnik1/yaamp/assets/116677879/d438ba89-bfaa-40a1-b584-06608fc72795)
При запуске программы выскакивает ошибка Failed to parse skin, не чего не могу сделать. Прошу помощи.

**Comment by umnik1** [comment]
Вообще в последней версии такого не должно быть, но попробуйте следующее:

> Откройте папку папку: C:\Users\user\AppData\Roaming\yaamp
> 
> (Только имя пользователя своё пропишите) и удалите файл skin.json
